### ISSUE TITLE
Requesting video sources aligned to the annotations provided

### ISSUE THREAD

**Issue by divineSix** [wywyWang/CoachAI-Projects#10]
I saw a previous issue where you mentioned that you do not intend to provide video links, instead using the names of matches in the folder. I searched the same, and found the videos on youtube, but I am running into some issues. 
- The videos on youtube are from the broadcast version, so how do I align the timestamps of the video in youtube to those in the CSV files shared. 
- Please provide an adequate README to deal with video downloading and preprocessing, as it is currently very difficult to experiment on the data you have provided without corresponding video frames. 

For example, a sample link is the first folder in the data you have provided, `AN_Se_Young_Akane_YAMAGUCHI_TotalEnergies_BWF_Thomas_and_Uber_Cup_Finals_2022_Semifinals`. 
- The youtube broadcast video for the same is [LINK](https://www.youtube.com/watch?v=NfrOuB5UTdI&list=PLA7ZcagI0frCTNTKtTmlyM0-ERbesXTD5&index=19)

The video is a very long sequence containing match shots, replays etc. So, I request your help in aligning the annotations you have provided with the video available. Or, instructions to download the appropriate pre-aligned video itself.

**Comment by wywyWang** [comment]
Hello,

Thanks for your interest in our work! We included video links in one of the PRs. Since there are some license issues, we are not able to provide those videos.

The annotation process was executed with the incorporation of the private annotation tool (see [the ShuttleSet paper](https://arxiv.org/abs/2306.04948) for more details)), which was not implemented by ourselves. Therefore, we cannot provide a detailed alignment strategy for preprocessing. 

Still, you can easily align the correct starting frame manually. Hope this helps. Thank you.
